on:
  workflow_dispatch:
    
concurrency:
  group: my-group
  cancel-in-progress: true

jobs:
  with-cancel-in-progress:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "start"
          sleep 60
          echo "done"
